---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  format: ./tasks/format.task.yml

tasks:
  default:
    silent: true
    deps: [aqua]
    cmds:
    - task: format
  aqua:
    run: once
    sources:
    - aqua/*.yaml
    - aqua/**/*.yaml
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - aqua install --all
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
