---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  format: ./tasks/format.task.yml
  linter: ./tasks/linter.task.yml

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    aliases: [all]
    deps: [aqua]
    cmds:
    - task: format
    - task: linter

  aqua:
    desc: '{{.TASK}}'
    sources:
    - aqua/*.yaml
    - aqua/**/*.yaml
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - aqua install --all
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
