---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  aqua:
    taskfile: aqua.task.yml
    internal: true

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    cmds:
    - task: shfmt
    - task: yamlfmt
    - task: pinact
    - task: dockerfmt

  shfmt:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    deps:
    - task: aqua:install
      silent: true
    sources:
    - '**/*.sh'
    - '**/*.bash'
    - '.*/**/*.sh'
    - '.*/**/*.bash'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - shfmt -w .
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  yamlfmt:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    deps:
    - task: aqua:install
      silent: true
    sources:
    - '**/*.yml'
    - '**/*.yaml'
    - '.*/**/*.yml'
    - '.*/**/*.yaml'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - yamlfmt .
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  pinact:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    deps:
    - task: aqua:install
      silent: true
    sources:
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - pinact run
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  dockerfmt:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    deps:
    - task: aqua:install
      silent: true
    sources:
    - '**/Dockerfile'
    - '.*/**/Dockerfile'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - dockerfmt -w -n Dockerfile
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
