---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    silent: true
    cmds:
    - task: editorconfig-checker

  editorconfig-checker:
    run: once
    sources:
    - '**/*'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - ec .
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
