---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    cmds:
    - task: editorconfig-checker
    - task: shellcheck
    - task: actionlint
    - task: ghalint
    - task: hadolint

  editorconfig-checker:
    desc: '{{.TASK}}'
    sources:
    - '**/*'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - ec .
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  shellcheck:
    desc: '{{.TASK}}'
    sources:
    - '**/*.sh'
    - '**/*.bash'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - fd -H -E .git/ -t f '.(sh|bash)' -X shellcheck
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  actionlint:
    desc: '{{.TASK}}'
    sources:
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - actionlint
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  ghalint:
    desc: '{{.TASK}}'
    sources:
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - ghalint run
    - ghalint act
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  hadolint:
    desc: '{{.TASK}}'
    sources:
    - 'Dockerfile'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - hadolint Dockerfile
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
